### ISSUE TITLE
Unhandled exceptions when trying to enqueue a message

### ISSUE THREAD

**Issue by brianfeucht** [weloytty/MSMQ.Messaging#4]
I have run into the following exceptiond when calling `MessageQueue.Send`.  Still trying to dive into the details of exactly what is going on.  I'll add more details to this issue as I find them.

```
System.InvalidCastException: Unable to cast object of type 'System.Runtime.InteropServices.GCHandle' to type 'System.UInt32'. 
at MQPROPS MSMQ.Messaging.Interop.MessagePropertyVariants.Lock() 
at void MSMQ.Messaging.MessageQueue.SendInternal(object obj, MessageQueueTransaction internalTransaction, MessageQueueTransactionType transactionType)
```

```
System.NullReferenceException: Object reference not set to an instance of an object. 
at void MSMQ.Messaging.Interop.MessagePropertyVariants.Unlock() 
at void MSMQ.Messaging.MessageQueue.SendInternal(object obj, MessageQueueTransaction internalTransaction, MessageQueueTransactionType transactionType)
```

We are running this on .NET 5.0.3

winver details:
![image](https://user-images.githubusercontent.com/1063445/117362205-d26e9f00-ae6f-11eb-936a-82b4add1e76b.png)

**Comment by weloytty** [comment]
Can I see which properties you are using to send?  The way I usually test is to ensure that the same code works the same way using both System.Messaging and MSMQ.Messaging, since I have tried to change nothing.

**Comment by brianfeucht** [comment]
We can close this.  I accidentally changed code that was previously a singleton so that it called into the MSMQ initialization on multiple threads in a concurrent fashion.  Switching it back to a singleton prevented the multiple calls and our code appears to be functioning as it did previously with `System.Messaging`
